// Generated by https://quicktype.io

export interface IPokemonListResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  IBasicPokemon[];
}

export interface IBasicPokemon {
    name: string;
    url:  string;
}
